import type { Locale } from "@/lib/i18n";
import type { AuthorityPage } from "@/lib/content/authority-pages-v31";

export type ExistingAuthorityPageKey = "technology" | "whiteBox" | "trust" | "company";

const pages: Record<"en" | "az" | "ru", Record<ExistingAuthorityPageKey, AuthorityPage>> = {
  en: {
    technology: {
      title: "AzeVSM AI: VSM-Class Artificial Intelligence Instead of Free Generation",
      lead: "AzevsmAI combines evidence, Azevsm Systems’ proprietary scientific-technical methodology, semantic ontology, product mathematics, and AzeVSM AI.",
      blocks: [
        { type: "heading", text: "What the VSM class means" },
        { type: "p", text: "VSM — Verifiable Structured Model — is the public AI class to which AzeVSM AI belongs. It is not a separate technology, product, platform, or standalone brand. VSM provides a safe external technological abstraction: structured, evidence-linked input and a reproducible calculated result rather than free-form text generation, without disclosing the internal mathematical implementation." },
        { type: "heading", text: "Proprietary scientific-technical methodology and semantic ontology" },
        { type: "p", text: "AzevsmAI is built on Azevsm Systems’ proprietary scientific-technical methodology and semantic ontology. The methodology defines analytical admissibility and the boundaries of the result; the semantic ontology provides a consistent meaning structure for the objects and relationships required by the platform. Their public description is limited to principles and does not expose protected internal implementation." },
        { type: "heading", text: "AzeVSM AI, the VSM class, and product mathematics" },
        { type: "p", text: "AzeVSM AI is the full name of Azevsm Systems’ proprietary artificial-intelligence technology, purpose-built for AzevsmAI. It belongs to the VSM — Verifiable Structured Model — AI class and operates in conjunction with the platform’s scientific-technical methodology, semantic ontology, and product mathematics. The AzeVSM AI calculation result is fixed within the applicable product; it is not generated by an LLM and does not depend on free-form language-model generation. The internal mathematical implementation remains protected intellectual property of Azevsm Systems." },
        { type: "heading", text: "Scientific interpretation layer" },
        { type: "p", text: "Within authorized post-calculation analytics, AzevsmAI applies a systems perspective and scientific reference frameworks from complex adaptive systems theory: nonlinear dynamics, feedback, system dynamics, network and graph representations, agent-based perspectives, adaptation, path dependence, and other formal frameworks. These help reveal the meaning of an already obtained result without replacing product mathematics or creating a second calculation." },
        { type: "heading", text: "Role of language models" },
        { type: "p", text: "Language models may support authorized functions within the platform, but they do not define the methodology, form or choose the calculation outcome, or independently alter a fixed result. An LLM is not AzeVSM AI and is not the source of the AzeVSM AI calculation result." },
        { type: "note", title: "Complexity inside — clarity outside", body: "The client does not need to understand the internal mechanics to use the result. The platform handles the complexity of structure, calculation, and analytical processing, while presenting a clear result, the evidence base, and authorized explanation externally." },
      ],
      actions: [
        { label: "Explore validation and reproducibility", href: "/validation-reproducibility" },
        { label: "View White Box", href: "/white-box" },
      ],
    },
    whiteBox: {
      title: "Explain the Result. Protect the Method.",
      lead: "Controlled explainability helps users understand the authorized basis of the result without transferring the internal calculation mechanics.",
      blocks: [
        { type: "p", text: "White Box operates after the result has been obtained and explains its authorized part within the permitted level of disclosure: the evidence basis, traceability, applicable limitations, context, and accessible result structure. It does not perform a second calculation or expose protected methodology or the internal technology of AzeVSM AI." },
        { type: "heading", text: "What may be explained" },
        { type: "list", items: ["the evidence basis of the result;", "coverage of materials and applicable limitations;", "authorized links between the result and analytical objects;", "traceability and the context of a specific execution;", "the structure of the result within the level available to the client."] },
        { type: "heading", text: "Depth depends on the product" },
        { type: "p", text: "In some products, evidential support and traceability are built into the core result system. In certain institutional packages, White Box may be a standalone object. The depth depends on the product, package, and authorized access level." },
        { type: "heading", text: "What remains protected" },
        { type: "p", text: "Formulas, weights, thresholds, internal variables, transformation rules, protected mappings, the internal calculation sequence, and other elements that would enable reconstruction of the methodology are not part of ordinary client disclosure." },
      ],
      actions: [
        { label: "Learn about the available level of explainability", href: "/contact" },
        { label: "View the principles of trust", href: "/trust" },
      ],
    },
    trust: {
      title: "A Result Can Be Used Seriously When Its Origin and Boundaries Are Clear",
      lead: "Versioning, traceability, reproducibility, and separation of authority operate as one trust system.",
      blocks: [
        { type: "table", rows: [
          ["The result is not manually created by an analyst\nA person cannot raise, lower, or replace the calculated outcome at their discretion.", "The result version is fixed\nThe result is linked to a specific execution, data set, and version of the rules."],
          ["Evidence retains its significance\nThe client can understand the substantiated basis on which the result was built.", "Explanation does not rewrite the calculation\nA report, presentation, navigator, or White Box does not create new mathematics."],
          ["Access is restricted\nClient data, internal artifacts, and protected methodology are separated by roles and environments.", "An unresolved question does not become certainty\nIf the necessary basis is absent, the system preserves the limitation instead of inventing a fact."],
        ]},
        { type: "heading", text: "Why this matters to the buyer" },
        { type: "p", text: "This architecture allows AzevsmAI to be used not only as a tool for internal diagnostics, but also as a more serious analytical layer before investment, corporate, or institutional review. Trust is built not on the promise that “artificial intelligence knows better,” but on discipline in how the result is formed." },
      ],
      actions: [
        { label: "Request a demonstration", href: "/contact" },
        { label: "Validation and reproducibility", href: "/validation-reproducibility" },
      ],
    },
    company: {
      title: "Azevsm Systems Builds Technology for Structured Assessment and Analytics",
      lead: "Creator, developer, and operator of AzevsmAI; developer of the proprietary scientific-technical methodology, semantic ontology, and AzeVSM AI — Azevsm Systems’ proprietary VSM-class AI technology.",
      blocks: [
        { type: "p", text: "Azevsm Systems develops AzevsmAI as an institutional analytical platform and technological analytical infrastructure for startups, companies, investors, and institutional participants. The company brings product development, scientific-technical methodology, semantic ontology, AzeVSM AI, research, trust, and the client digital environment together within one system." },
        { type: "heading", text: "What we are building" },
        { type: "p", text: "The goal is not to automate report writing, but to turn the analytical cycle itself into a technological process: from evidence and structuring of the object to the calculated result, systems explanation, and a set of materials suitable for practical use." },
        { type: "heading", text: "Research foundation" },
        { type: "p", text: "Development of the platform is based on scientific-technical methodology, semantic ontology, formal product models, systems analysis, work with uncertainty, and reproducibility research. Scientific and systems frameworks are applied within the analytical tasks and products for which they are provided by the methodology and the relevant sources." },
        { type: "heading", text: "The market we serve" },
        { type: "p", text: "Azevsm Systems focuses on tasks that require more than a quick textual answer: preliminary assessment of investment flow, a structured view of a startup or company, institutional analysis, specialized analytics, and controlled explainability." },
      ],
      actions: [
        { label: "Contact Azevsm Systems", href: "/contact" },
        { label: "News and research", href: "/insights" },
      ],
    },
  },
  az: {
    technology: {
      title: "AzeVSM AI: sərbəst generasiya əvəzinə VSM sinifli süni intellekt",
      lead: "AzevsmAI sübutları, Azevsm Systems-in öz elmi-texniki metodologiyasını, semantik ontologiyasını, məhsul riyaziyyatını və AzeVSM AI-ni birləşdirir.",
      blocks: [
        { type: "heading", text: "VSM sinfi nə deməkdir" },
        { type: "p", text: "VSM — Verifiable Structured Model — yoxlanıla bilən strukturlaşdırılmış model. Açıq təsvir səviyyəsində VSM AzeVSM AI-nin aid olduğu süni intellekt sinfini bildirir. Bu, ayrıca texnologiya, məhsul, platforma və ya müstəqil brend deyil. VSM təhlükəsiz xarici texnoloji abstraksiya rolunu oynayır: sərbəst mətn generasiyası əvəzinə strukturlaşdırılmış, sübutlarla əlaqələndirilmiş giriş və təkrarlana bilən hesablama nəticəsi — daxili riyazi reallaşdırmanı açıqlamadan." },
        { type: "heading", text: "Öz elmi-texniki metodologiyası və semantik ontologiyası" },
        { type: "p", text: "AzevsmAI Azevsm Systems-in öz elmi-texniki metodologiyası və semantik ontologiyası üzərində qurulub. Metodologiya analitik uyğunluq qaydalarını və nəticənin sərhədlərini müəyyən edir; semantik ontologiya isə platforma üçün zəruri olan obyekt və əlaqələrin vahid məna strukturunu təmin edir. Onların açıq təsviri prinsiplərlə məhdudlaşır və qorunan daxili reallaşdırmanı açıqlamır." },
        { type: "heading", text: "AzeVSM AI, VSM sinfi və məhsul riyaziyyatı" },
        { type: "p", text: "AzeVSM AI Azevsm Systems-in AzevsmAI üçün xüsusi olaraq yaratdığı öz süni intellekt texnologiyasının tam adıdır. O, VSM — Verifiable Structured Model — yoxlanıla bilən strukturlaşdırılmış model sinfinə aiddir və platformanın elmi-texniki metodologiyası, semantik ontologiyası və məhsul riyaziyyatı ilə birlikdə işləyir. AzeVSM AI-nin hesablama nəticəsi tətbiq olunan məhsul daxilində sabitləşdirilir; nəticə LLM tərəfindən generasiya edilmir və dil modelinin sərbəst generasiyasından asılı deyil. Daxili riyazi reallaşdırma Azevsm Systems-in qorunan əqli mülkiyyəti olaraq qalır." },
        { type: "heading", text: "Elmi interpretasiya qatı" },
        { type: "p", text: "İcazə verilmiş hesablamadan sonrakı analitika çərçivəsində AzevsmAI sistem baxışından və mürəkkəb adaptiv sistemlər nəzəriyyəsinin elmi istiqamətlərindən istifadə edir: qeyri-xətti dinamika, əks əlaqələr, sistem dinamikası, şəbəkə və qraf təqdimatları, agent əsaslı baxış, adaptasiya, trayektoriyadan asılılıq və digər formal çərçivələr. Onlar məhsul riyaziyyatını əvəz etmədən və ikinci hesablama yaratmadan artıq əldə olunmuş nəticənin mənasını açmağa kömək edir." },
        { type: "heading", text: "Dil modellərinin rolu" },
        { type: "p", text: "Dil modelləri platforma daxilində icazə verilmiş funksiyaları dəstəkləyə bilər, lakin metodologiyanı müəyyən etmir, hesablama nəticəsini formalaşdırmır və seçmir, sabitləşdirilmiş nəticəni müstəqil şəkildə dəyişə bilməz. LLM AzeVSM AI deyil və AzeVSM AI hesablama nəticəsinin mənbəyi deyil." },
        { type: "note", title: "Daxildə mürəkkəblik — xaricdə aydınlıq", body: "Nəticədən istifadə etmək üçün müştərinin daxili mexanikanı bilməsi tələb olunmur. Platforma strukturun, hesablamanın və analitik prosesin mürəkkəbliyini öz üzərinə götürür, xaricə isə aydın nəticə, sübut bazası və icazə verilmiş izah təqdim edir." },
      ],
      actions: [
        { label: "Yoxlama və təkrarlana bilməni öyrənmək", href: "/validation-reproducibility" },
        { label: "White Box-a baxmaq", href: "/white-box" },
      ],
    },
    whiteBox: {
      title: "Nəticəni izah etmək. Metodu qorumaq.",
      lead: "Nəzarət olunan izah edilə bilmə daxili hesablama mexanikasını ötürmədən nəticənin icazə verilmiş əsasını anlamağa kömək edir.",
      blocks: [
        { type: "p", text: "White Box nəticə əldə olunduqdan sonra işləyir və onun icazə verilmiş hissəsini müəyyən edilmiş açıqlama səviyyəsində izah edir: sübut bazasını, izlənəbilərliyi, tətbiq olunan məhdudiyyətləri, konteksti və əlçatan nəticə strukturunu. O, ikinci hesablama aparmır və qorunan metodologiyanı və ya AzeVSM AI-nin daxili texnologiyasını açıqlamır." },
        { type: "heading", text: "Nələr izah oluna bilər" },
        { type: "list", items: ["nəticənin sübut bazası;", "materialların əhatə dairəsi və tətbiq olunan məhdudiyyətlər;", "nəticənin analitik obyektlərlə icazə verilmiş əlaqələri;", "konkret icranın izlənəbilərliyi və konteksti;", "müştəri üçün əlçatan səviyyə daxilində nəticənin strukturu."] },
        { type: "heading", text: "Dərinlik məhsuldan asılıdır" },
        { type: "p", text: "Bəzi məhsullarda sübutlarla əsaslandırılma və izlənəbilərlik əsas nəticə sisteminə daxildir. Ayrı-ayrı institusional paketlərdə White Box müstəqil obyekt ola bilər. Dərinlik məhsuldan, paketdən və icazə verilmiş giriş səviyyəsindən asılıdır." },
        { type: "heading", text: "Nələr qorunan olaraq qalır" },
        { type: "p", text: "Metodikanın bərpasına imkan verə biləcək düsturlar, çəkilər, hədlər, daxili dəyişənlər, çevirmə qaydaları, qorunan uyğunluqlar, hesablamanın daxili ardıcıllığı və digər elementlər adi müştəri açıqlamasına daxil deyil." },
      ],
      actions: [
        { label: "Əlçatan izah səviyyəsi haqqında öyrənmək", href: "/contact" },
        { label: "Etimad prinsiplərinə baxmaq", href: "/trust" },
      ],
    },
    trust: {
      title: "Nəticənin mənşəyi və sərhədləri aydın olduqda ondan ciddi şəkildə istifadə etmək mümkündür",
      lead: "Versiyalaşdırma, izlənəbilərlik, təkrarlana bilmə və səlahiyyətlərin ayrılması vahid etimad sistemi kimi işləyir.",
      blocks: [
        { type: "table", rows: [
          ["Nəticəni analitik əl ilə formalaşdırmır\nİnsan öz mülahizəsinə əsasən hesablama nəticəsini artıra, azalda və ya əvəz edə bilməz.", "Nəticənin versiyası sabitləşdirilir\nNəticə konkret icra, məlumat dəsti və qaydaların versiyası ilə əlaqələndirilir."],
          ["Sübutlar öz əhəmiyyətini qoruyur\nMüştəri nəticənin hansı təsdiqlənmiş əsas üzərində qurulduğunu anlaya bilər.", "İzah hesablamanı yenidən yazmır\nHesabat, təqdimat, naviqator və ya White Box yeni riyaziyyat yaratmır."],
          ["Giriş məhduddur\nMüştəri məlumatları, daxili artefaktlar və qorunan metodologiya rollar və mühitlər üzrə ayrılır.", "Həll olunmamış sual əminliyə çevrilmir\nZəruri əsas yoxdursa, sistem uydurulmuş fakt əvəzinə məhdudiyyəti qoruyur."],
        ]},
        { type: "heading", text: "Bu, alıcı üçün nə üçün vacibdir" },
        { type: "p", text: "Belə arxitektura AzevsmAI-dən yalnız daxili diaqnostika vasitəsi kimi deyil, həm də investisiya, korporativ və ya institusional baxışdan əvvəl daha ciddi analitik qat kimi istifadə etməyə imkan verir. Etimad “süni intellekt daha yaxşı bilir” vədinə deyil, nəticənin formalaşdırılması intizamına əsaslanır." },
      ],
      actions: [
        { label: "Demonstrasiya tələb etmək", href: "/contact" },
        { label: "Yoxlama və təkrarlana bilmə", href: "/validation-reproducibility" },
      ],
    },
    company: {
      title: "Azevsm Systems strukturlaşdırılmış qiymətləndirmə və analitika texnologiyası yaradır",
      lead: "AzevsmAI-nin yaradıcısı, tərtibatçısı və operatoru; öz elmi-texniki metodologiyasının, semantik ontologiyasının və AzeVSM AI-nin — Azevsm Systems-in VSM sinifli öz süni intellekt texnologiyasının — tərtibatçısı.",
      blocks: [
        { type: "p", text: "Azevsm Systems AzevsmAI-ni startaplar, şirkətlər, investorlar və institusional iştirakçılar üçün institusional analitik platforma və texnoloji analitik infrastruktur kimi inkişaf etdirir. Şirkət məhsul hazırlığını, elmi-texniki metodologiyanı, semantik ontologiyanı, AzeVSM AI-ni, tədqiqat fəaliyyətini, etimadı və müştərinin rəqəmsal mühitini vahid sistemdə birləşdirir." },
        { type: "heading", text: "Biz nə qururuq" },
        { type: "p", text: "Məqsəd hesabat yazmağı avtomatlaşdırmaq deyil, analitik dövrün özünü texnoloji prosesə çevirməkdir: sübutlardan və obyektin strukturlaşdırılmasından hesablama nəticəsinə, sistem izahına və praktiki istifadə üçün yararlı materiallar toplusuna qədər." },
        { type: "heading", text: "Tədqiqat əsası" },
        { type: "p", text: "Platformanın inkişafı elmi-texniki metodologiyaya, semantik ontologiyaya, formal məhsul modellərinə, sistem təhlilinə, qeyri-müəyyənliklə işə və təkrarlana bilmə üzrə tədqiqatlara əsaslanır. Elmi və sistem çərçivələri yalnız metodologiya və müvafiq mənbələrdə nəzərdə tutulduğu analitik tapşırıq və məhsullar daxilində tətbiq edilir." },
        { type: "heading", text: "Hansı bazar üçün" },
        { type: "p", text: "Azevsm Systems sürətli mətn cavabından daha çoxunu tələb edən tapşırıqlara yönəlir: investisiya axınının ilkin qiymətləndirilməsi, startap və ya şirkətə strukturlaşdırılmış baxış, institusional təhlil, ixtisaslaşmış analitika və nəzarət olunan izah edilə bilmə." },
      ],
      actions: [
        { label: "Azevsm Systems ilə əlaqə saxlamaq", href: "/contact" },
        { label: "Xəbərlər və tədqiqatlar", href: "/insights" },
      ],
    },
  },
  ru: {
    technology: {
      title: "AzeVSM AI: технология класса VSM вместо свободной генерации",
      lead: "AzevsmAI объединяет доказательства, собственную научно-техническую методологию Azevsm Systems, семантическую онтологию, продуктовую математику и AzeVSM AI.",
      blocks: [
        { type: "heading", text: "Что означает класс VSM" },
        { type: "p", text: "VSM — Verifiable Structured Model — проверяемая структурированная модель. В публичном описании VSM обозначает класс искусственного интеллекта, к которому относится AzeVSM AI. Это не отдельная технология, продукт, платформа или самостоятельный бренд. Класс VSM служит безопасным уровнем технологической абстракции: структурированный, доказательно связанный вход и воспроизводимый расчетный результат вместо свободной генерации текста — без раскрытия внутренней математической реализации." },
        { type: "heading", text: "Собственная научно-техническая методология и семантическая онтология" },
        { type: "p", text: "AzevsmAI строится на собственной научно-технической методологии и семантической онтологии Azevsm Systems. Методология задает правила аналитической допустимости и границы результата; семантическая онтология обеспечивает единое смысловое представление объектов и связей, необходимое для работы платформы. Их публичное описание ограничено принципами и не раскрывает защищенную внутреннюю реализацию." },
        { type: "heading", text: "AzeVSM AI, класс VSM и продуктовая математика" },
        { type: "p", text: "AzeVSM AI — полное название собственной технологии искусственного интеллекта Azevsm Systems, специально разработанной для AzevsmAI. Она относится к классу VSM — Verifiable Structured Model — и работает в связке с научно-технической методологией, семантической онтологией и продуктовой математикой платформы. Расчетный результат AzeVSM AI фиксируется в рамках применимого продукта; он не генерируется LLM и не зависит от свободной генерации языковой модели. Внутренняя математическая реализация остается защищенной интеллектуальной собственностью Azevsm Systems." },
        { type: "heading", text: "Научный слой интерпретации" },
        { type: "p", text: "В составе разрешенной пострасчетной аналитики AzevsmAI применяет системный взгляд и научные ориентиры теории сложных адаптивных систем: нелинейную динамику, обратные связи, системную динамику, сетевые и графовые представления, агентный взгляд, адаптацию, зависимость от траектории и другие формальные рамки. Они помогают раскрывать смысл уже полученного результата, не заменяя продуктовую математику и не создавая второй расчет." },
        { type: "heading", text: "Роль языковых моделей" },
        { type: "p", text: "Языковые модели могут поддерживать разрешенные функции внутри платформы, но они не определяют методологию, не формируют и не выбирают расчетный исход и не могут самостоятельно изменить зафиксированный результат. LLM не является AzeVSM AI и не является источником расчетного результата AzeVSM AI." },
        { type: "note", title: "Сложность внутри — ясность снаружи", body: "Клиенту не требуется понимать внутреннюю механику, чтобы пользоваться результатом. Платформа берет на себя сложность структуры, расчета и аналитического процесса, а наружу выводит понятный результат, доказательную основу и разрешенное объяснение." },
      ],
      actions: [
        { label: "Изучить проверку и воспроизводимость", href: "/validation-reproducibility" },
        { label: "Посмотреть White Box", href: "/white-box" },
      ],
    },
    whiteBox: {
      title: "Объяснить результат. Защитить метод.",
      lead: "Контролируемая объяснимость помогает понять разрешенную основу результата без передачи внутренней расчетной механики.",
      blocks: [
        { type: "p", text: "White Box работает после получения результата и объясняет его разрешенную часть в пределах установленного уровня раскрытия: доказательную основу, прослеживаемость, применимые ограничения, контекст и доступную структуру результата. Он не выполняет второй расчет и не раскрывает защищенную методологию или внутреннюю технологию AzeVSM AI." },
        { type: "heading", text: "Что может быть объяснено" },
        { type: "list", items: ["доказательная основа результата;", "охват материалов и применимые ограничения;", "разрешенные связи результата с аналитическими объектами;", "прослеживаемость и контекст конкретного запуска;", "структура результата в пределах доступного клиенту уровня."] },
        { type: "heading", text: "Глубина зависит от продукта" },
        { type: "p", text: "В одних продуктах доказательность и прослеживаемость встроены в основную систему результата. В отдельных институциональных пакетах White Box может быть самостоятельным объектом. Глубина зависит от продукта, пакета и разрешенного уровня доступа." },
        { type: "heading", text: "Что остается защищенным" },
        { type: "p", text: "Формулы, веса, пороги, внутренние переменные, правила преобразования, защищенные соответствия, внутренняя последовательность расчета и другие элементы, позволяющие восстановить методику, не относятся к обычному клиентскому раскрытию." },
      ],
      actions: [
        { label: "Узнать о доступном уровне объяснимости", href: "/contact" },
        { label: "Посмотреть принципы доверия", href: "/trust" },
      ],
    },
    trust: {
      title: "Результат можно использовать серьезно, когда его происхождение и границы понятны",
      lead: "Версионность, прослеживаемость, воспроизводимость и разделение полномочий работают как единая система доверия.",
      blocks: [
        { type: "table", rows: [
          ["Результат формирует не аналитик вручную\nЧеловек не может по своему усмотрению повысить, понизить или заменить расчетный исход.", "Версия результата фиксируется\nРезультат связан с конкретным запуском, набором данных и версией правил."],
          ["Доказательства сохраняют значение\nКлиент может понимать, на какой подтвержденной основе построен результат.", "Объяснение не переписывает расчет\nОтчет, презентация, навигатор или White Box не создают новую математику."],
          ["Доступ ограничен\nКлиентские данные, внутренние артефакты и защищенная методология разделены по ролям и контурам.", "Нерешенный вопрос не превращается в уверенность\nЕсли необходимое основание отсутствует, система сохраняет ограничение вместо выдуманного факта."],
        ]},
        { type: "heading", text: "Почему это важно для покупателя" },
        { type: "p", text: "Такая архитектура позволяет использовать AzevsmAI не только как средство внутренней диагностики, но и как более серьезный аналитический слой перед инвестиционным, корпоративным или институциональным рассмотрением. Доверие строится не на обещании «искусственный интеллект знает лучше», а на дисциплине формирования результата." },
      ],
      actions: [
        { label: "Запросить демонстрацию", href: "/contact" },
        { label: "Проверка и воспроизводимость", href: "/validation-reproducibility" },
      ],
    },
    company: {
      title: "Azevsm Systems создает технологию структурированной оценки и аналитики",
      lead: "Создатель, разработчик и оператор AzevsmAI; разработчик собственной научно-технической методологии, семантической онтологии и AzeVSM AI — собственной технологии искусственного интеллекта класса VSM.",
      blocks: [
        { type: "p", text: "Azevsm Systems развивает AzevsmAI как институциональную аналитическую платформу и технологическую аналитическую инфраструктуру для стартапов, компаний, инвесторов и институциональных участников. Компания объединяет продуктовую разработку, научно-техническую методологию, семантическую онтологию, AzeVSM AI, исследовательскую работу, доверие и клиентскую цифровую среду в одной системе." },
        { type: "heading", text: "Что мы строим" },
        { type: "p", text: "Цель — не автоматизировать написание отчетов, а технологизировать сам аналитический цикл: от доказательств и структурирования объекта до расчетного результата, системного объяснения и набора материалов, пригодных для практического использования." },
        { type: "heading", text: "Исследовательская основа" },
        { type: "p", text: "Развитие платформы опирается на научно-техническую методологию, семантическую онтологию, формальные продуктовые модели, системный анализ, работу с неопределенностью и исследования воспроизводимости. Научные и системные рамки применяются в пределах тех аналитических задач и продуктов, для которых они предусмотрены методологией и соответствующими источниками." },
        { type: "heading", text: "Для какого рынка" },
        { type: "p", text: "Azevsm Systems ориентируется на задачи, где требуется больше, чем быстрый текстовый ответ: предварительная оценка инвестиционного потока, структурированный взгляд на стартап или компанию, институциональный анализ, специализированная аналитика и контролируемая объяснимость." },
      ],
      actions: [
        { label: "Связаться с Azevsm Systems", href: "/contact" },
        { label: "Новости и исследования", href: "/insights" },
      ],
    },
  },
};

export function getExistingAuthorityPage(locale: Locale, key: ExistingAuthorityPageKey): AuthorityPage | null {
  if (locale !== "en" && locale !== "az" && locale !== "ru") return null;
  return pages[locale][key];
}
